import type { Metadata } from "next";

// These styles apply to every route in the application
import "@/app/globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Startup Junction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
