export const team2022 = {
  presidents: [{
    name: "AMIT KUMAR BAHETI",
    image: "Amit.jpg",
    post: "VICE PRESIDENT E-CELL",
    email: "mailto:amit.krbaheti.eee19@iitbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/amitkumarbaheti/",
    twitter: "https://twitter.com/amit_baheti_",
  },
  {
    name: "TANAYA MUJUMDAR",
    image: "Tanaya.jpg",
    post: "ASSOCIATE VICE PRESIDENT E-CELL",
    email: "mailto:mujumdartanaya@gmail.com",
    linkedin: "https://www.linkedin.com/in/tanaya-mujumdar-80aa17207",
    twitter: "https://twitter.com/TanayaMujumdar",
  },],
  verticalHeads: [{
    name: "TANYA GUPTA",
    image: "Tanya.jpeg",
    position: "BRANDING HEAD",
    email: "mailto:tanya.gupta.che20@itbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/tanya-gupta-215942214",
    twitter:
      "https://twitter.com/TanyaGu27136914?t=pBdV1Hb-cSR19h2Zcqr9Yg&s=08",
  },
  {
    name: "PARTH GUPTA",
    image: "Parth.jpg",
    position: "SAP HEAD",
    email: "mailto:parthsanjeev.gupta.che20@itbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/parthgupta03/",
    twitter: "https://twitter.com/ParthG03",
  },
  {
    name: "ASHWAT KUMAR SINGH",
    image: "Ashwat.jpg",
    position: "TECH HEAD",
    email: "mailto:ashwat.kumarsingh.met20@itbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/ashwat-singh/",
    twitter: "https://twitter.com/ashwat_singh",
  },
  {
    name: "SHREYA JAIN",
    image: "Shreya.jpg",
    position: "EVENTS HEAD",
    email: "mailto:shreya.jain.cd.eee20@iitbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/shreya-jain-/",
    twitter: "https://twitter.com/shreyaj90",
  },
  {
    name: "VANSHIKA GUPTA",
    image: "Vanshika.jpg",
    position: "STRATEGIC RELATIONS HEAD",
    email: "mailto:vanshika.gupta.met20@iitbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/vanshika-gupta-299001201",
    twitter: "https://twitter.com/vanshika130502",
  },
  {
    name: "DIVYANSH THAKRE",
    image: "Divyansh.jpg",
    position: "INNOVATION & INCUBATION HEAD",
    email: "mailto:divyansh.thakre.civ20@itbhu.ac.in",
    linkedin: "https://www.linkedin.com/in/divyanshthakre/",
    twitter: "https://twitter.com/Divyansh_03",
  },]
}