export const team2025 = {
  year: "Team2025",
  session: "2025-26",
  presidents: [
    {
      name: "MRINALINI SAPPATTI",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/vp.jpg",
      post: "VICE PRESIDENT E-CELL",
      email: "mailto:sappatti.mrinalini.met22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/mrinalini-sappatti",
    },
    {
      name: "VANSH AGARWAL",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/avp.jpg",
      post: "ASSOCIATE VICE PRESIDENT E-CELL",
      email: "mailto:vansh.agarwal.bce22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/vansh-agarwal-6a9901262",
    }
  ],
  verticalHeads: [
    {
      name: "GOURAV PANDEY",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/saphead.jpg",
      position: "STARTUP ASSISTANCE PROGRAM HEAD",
      email: "mailto:gourav.pandey.phe23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/gouravrpandey",
    },
    {
      name: "OPPILAN INIYAN",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/saphead2.jpg",
      position: "STARTUP ASSISTANCE PROGRAM HEAD",
      email: "mailto:oppilan.iniyan.bme23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/oppilan-iniyan-0bb73019a",
    },
    {
      name: "ANWESH MOHANTY",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/brandinghead1.jpg",
      position: "BRANDING HEAD",
      email: "mailto:anwesh.mohanty.bce23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/anwesh-mohanty-01a815216",
    },
    {
      name: "PM MEENAKSHI",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/brandinghead2.jpg",
      position: "BRANDING HEAD",
      email: "mailto:pm.meenakshi.civ23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/pm-meenakshi-8752872a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
    {
      name: "SUBHENDU SARKAR",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/designhead.jpg",
      position: "DESIGN HEAD",
      email: "mailto:subhendu.sarkar.ece23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/sarkarsarvasya",
    },
    {
      name: "ASHISH ANAND",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/eventshead1.jpg",
      position: "EVENTS HEAD",
      email: "mailto:ashish.anand.cd.civ23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/ashish-anand-5619632a8",
    },
    {
      name: "DEEPALI GUPTA",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/eventshead2.jpg",
      position: "EVENTS HEAD",
      email: "mailto:deepali.gupta.cd.civ23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/deepali-gupta-b29a82294",
    },
    {
      name: "KRISH KUMAR",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/inihead.jpg",
      position: "INNOVATION & INCUBATION HEAD",
      email: "mailto:krish.kumar.civ23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/krish-kumar",
    },
    {
      name: "SAKSHAM MODI",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/snohead.jpg",
      position: "STRATEGY & OUTREACH HEAD",
      email: "mailto:saksham.modi.civ23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/saksham280504",
    },
      {
      name: "V SAI VIVEK",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/snohead1.jpg",
      position: "STRATEGY & OUTREACH HEAD",
      email: "mailto:vsai.vivek.cer23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/v-sai-vivek",
    },
    {
      name: "PARTH PURWAR",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/relationshead.jpg",
      position: "PUBLIC RELATIONS HEAD",
      email: "mailto:parth.purwar.ece23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/parth-purwar-32b315282",
    },
    {
      name: "GEETHANSH RATHORE",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/relationshead2.png",
      position: "STRATEGIC RELATIONS HEAD",
      email: "mailto:geethansh.rathore.phe23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/geethanshr",
    },
    {
      name: "AASTHIK RAO",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/relationshead3.jpg",
      position: "MARKETING HEAD",
      email: "mailto:aasthik.raou.min23@iitbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/aasthik-rao-290733288",
    },
    {
      name: "NITYA SHUKLA",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/relationhead4.jpg",
      position: "MARKETING HEAD",
      email: "mailto:nitya.shukla.cdche23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/nitya-shukla-0a0638295",
    },
    {
      name: "RASESH SHETTY",
      image: "https://ik.imagekit.io/ecelliitbhu/website/ecell-team/techhead.jpg",
      position: "TECH HEAD",
      email: "mailto:raseshudayak.shetty.mat23@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/rasesh-shetty",
    },
  ]
}
