export const team2024 = {
  presidents: [
    {
      name: "PRANJALI YADAV",
      image: "PRANJALIYADAV.png",
      post: "VICE PRESIDENT E-CELL",
      email: "mailto:pranjali.yadav.cd.mec21@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/pranjali-yadav-39583022b/",
    },
    {
      name: "ATHARV PATIL",
      image: "ATHARV PATIL.png",
      post: "ASSOCIATE VICE PRESIDENT E-CELL",
      email: "mailto:atharv.patil.che21@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/atharv-patil/",
    }
  ],
  verticalHeads: [
    {
      name: "SIDHANTH SINGH",
      image: "SIDHANTH.png",
      position: "STARTUP ASSISTANCE PROGRAM HEAD",
      email: "mailto:sidhanth.singh.che22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/sidhanth-singh-b29a0624b/",
    },
    {
      name: "JAHNAVI KHOSLA",
      image: "JAHNAVI.png",
      position: "STARTUP ASSISTANCE PROGRAM HEAD",
      email: "mailto:jahnavi.khosla.cd.eee22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/jahnavi-khosla-5aa91124b/",
    },
    {
      name: "VANSH AGARWAL",
      image: "VANSH.png",
      position: "BRANDING HEAD",
      email: "mailto:vansh.agarwal.bce22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/vansh-agarwal-6a9901262/",
    },
    {
      name: "CHETANSI",
      image: "CHETANSI.png",
      position: "BRANDING HEAD",
      email: "mailto:chetansi.student.civ22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/chetansi-670797274/",
    },
    {
      name: "MAYURESH CHIMANKAR",
      image: "MAYURESH.png",
      position: "DESIGN HEAD",
      email: "mailto:mayuresh.chimankar.cse22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/mayuresh-chimankar/",
    },
    {
      name: "VANDAN DEULKAR",
      image: "VANDAN.png",
      position: "EVENTS HEAD",
      email: "mailto:vandan.deulkar.che22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/vandan-deulkar-05777a256/",
    },
    {
      name: "MRINALINI SAPPATTI",
      image: "MRINALINI.png",
      position: "EVENTS HEAD",
      email: "mailto:sappatti.mrinalini.met22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/mrinalini-sappatti/",
    },
    {
      name: "ARYAN DAHIYA",
      image: "ARYAN D.png",
      position: "INNOVATION & INCUBATION HEAD",
      email: "mailto:aryan.student.phe22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/aryan-dahiya-72a131257/",
    },
    {
      name: "ARNAAV SHAH",
      image: "ARNAAV.png",
      position: "STRATEGY & OUTREACH HEAD",
      email: "mailto:arnaav.shah.mec22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/arnaav-shah-1b566125a/",
    },
    {
      name: "ANSH DEOL",
      image: "ANSH.jpg",
      position: "MARKETING HEAD",
      email: "mailto:ansh.deol.phe22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/anshdeol/",
    },
    {
      name: "ARYAN PENDKE",
      image: "ARYAN P.png",
      position: "MARKETING HEAD",
      email: "mailto:aryan.pendke.che22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/aryan-pendke-963974255/",
    },
    {
      name: "HARSH PANT",
      image: "HARSH PANT.png",
      position: "PUBLIC RELATION HEAD",
      email: "mailto:harsh.pant.phe22@iitbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/harsh-pant-178a03276/",
    },
    {
      name: "TIRTH BHAYANI",
      image: "TIRTH.png",
      position: "STRATEGIC RELATIONS HEAD",
      email: "mailto:tirth.bhayani.cse22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/tirthbhayani1/",
    },
    {
      name: "SHIVANSHU RANJAN",
      image: "SHIVANSHU.png",
      position: "TECH HEAD",
      email: "mailto:shivanshu.ranjan.che22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/shivanshu-ranjan-0671a3245/",
    },
    {
      name: "R ASHVITA",
      image: "R.ASHVITA.png",
      position: "TECH HEAD",
      email: "mailto:r.ashvita.mec22@itbhu.ac.in",
      linkedin: "https://www.linkedin.com/in/ashvita-ramanan-285239261/",
    }
  ]
}