export const team2021 = {
    year: "Team2021",
    session: "2021-22",
    presidents: [{
        name: "HARSHIT SHUKLA",
        image: "HARSHIT_SHUKLA.jpg",
        post: "VICE PRESIDENT E-CELL",
        email: "mailto:harshitshukla.eee18@iitbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/harshitshuklaiitbhu/",
        twitter: "https://twitter.com/harshit_tw",
    },
    {
        name: "AMIT KUMAR BAHETI",
        image: "AMIT_KUMAR_BAHETI.jpg",
        post: "ASSOCIATE VICE PRESIDENT E-CELL",
        email: "mailto:amit.krbaheti.eee19@iitbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/amitkumarbaheti/",
        twitter: "https://twitter.com/amit_baheti_",
    },],
    verticalHeads: [{
        name: "AATISHYA SOOD",
        image: "AATISHYA_SOOD.jpg",
        position: "WEB AND BRANDING HEAD",
        email: "mailto:aatishya.sood.met19@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/aatishya-sood-5699081a7",
        twitter: "https://twitter.com/aatishya?s=09",
    },
    {
        name: "AMIT KUMAR JHA",
        image: "AMIT_KUMAR_JHA.jpg",
        position: "SAP HEAD",
        email: "mailto:amit.kumarjha.met19@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/amit-jha-96022618b",
        twitter: "https://twitter.com/AmitKum17723914",
    },
    {
        name: "ANSHUL SINGH",
        image: "ANSHUL_SINGH.jpeg",
        position: "STUDENT BODY HEAD, CISCO THINGQ",
        email: "mailto:anshul.singh.met19@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/anshul-singh-b58790197",
        twitter: "https://twitter.com/AnshulS61107731",
    },
    {
        name: "ABHISHEK NAVNEET FARDE",
        image: "ABHISHEK_NAVNEET_FARDE.jpeg",
        position: "EVENTS HEAD",
        email: "mailto:abhisheknfarde.mec18@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/abhishek-farde-95b871194",
        twitter: "https://twitter.com/AbhishekFarde?s=09",
    },
    {
        name: "ANMOL GOYAL",
        image: "ANMOL_GOYAL.jpeg",
        position: "STRATEGIC RELATIONS HEAD",
        email: "mailto:anmol.goyal.civ19@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/anmol-goyal-324852194",
        twitter: "https://twitter.com/AnmolGo37120796",
    },
    {
        name: "ARSHAD KHAN",
        image: "ARSHAD_KHAN.jpeg",
        position: "RIEU HEAD",
        email: "mailto:mdarshadkhan.bme18@itbhu.ac.in",
        linkedin: "https://www.linkedin.com/in/mohammed-arshad-khan-0b766a191",
        twitter: "https://twitter.com/mak640477",
    },]
}